Switch to SHA256 for ssl.com signatures
Using SHA512 results in the error:

net.jsign.bouncycastle.operator.RuntimeOperatorException: exception obtaining signature: java.security.GeneralSecurityException: java.io.IOException: invalid_request: invalid signature algorithm in request

It seems ssl.com does not support sha512 algorithms when signing windows
executables.

DAFFODIL-3090